platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-cfcr-etcd-release/ci/scripts/create-final-release.sh

params:
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""
  BRANCH: "master"

inputs:
  - name: git-cfcr-etcd-release
  - name: cfcr-etcd-version
outputs:
  - name: cfcr-etcd-release
  - name: git-cfcr-etcd-release-output
